#!/usr/bin/env zsh
function() {
	zmodload zsh/parameter
	setopt extended_glob
	local this_file="${funcsourcetrace[1]%:*}"
	local cur_dir="${${this_file:A:h}:h}"
	mkdir -p ~/.fonts
	cp -a ${cur_dir}/fonts/**/*.(ttf)(.N) ~/.fonts
	cd ~/.fonts
	mkfontscale
	mkfontdir
	fc-cache -fv ~/.fonts
}
