export GTK_IM_MODULE="cedilla"
export VIMINIT="source $HOME/.vim/vimrc"
export PYTHONSTARTUP="$HOME/.pythonrc"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export WINEARCH="win32"
export WINEPREFIX="$HOME/.wine"
export EDITOR="vim"
export VBOX_USER_HOME="$HOME/.virtualbox"
