#!/bin/sh

# For some strange reason, in FreeBSD some of the commands here only
# work when output is redirected, if openbox is started using slim
exec > /dev/null
exec 2>&1

if [ -f "$HOME/.config/openbox/background.png" ] && which xsetbg > /dev/null 2>&1; then
	xsetbg "$HOME/.config/openbox/background.png"
fi

if which VBoxClient-all > /dev/null 2>&1; then
	# If running as virtualbox guest, initialize guest additions features
	VBoxClient-all
fi

tint2 &
urxvt &
